#!/usr/bin/env perl
use warnings;
use strict;
use FindBin qw($Bin);
use lib "$Bin/lib";
use Getopt::Long;
use Phylosift::Phylosift;
use Carp;
use Phylosift::Utilities qw(debug);
use Phylosift::UpdateDB;
die "Usage: phylosift_dbupdate.pl <data repository path>" unless @ARGV == 1;
my $repository               = $ARGV[0];
my $ebi_repository           = $repository . "/ebi";
my $ncbi_draft_repository    = $repository . "/ncbi_draft";
my $ncbi_finished_repository = $repository . "/ncbi_finished";
my $local_repository         = $repository . "/local";
my $result_repository        = $repository . "/processed";
my $marker_dir               = $repository . "/markers";
my $newObject                = new Phylosift::Phylosift();
my @new_genomes = ();
$newObject->readPhylosiftConfig();
Phylosift::Utilities::dataChecks($newObject);
Phylosift::UpdateDB::get_ebi_genomes($ebi_repository);
Phylosift::UpdateDB::get_ncbi_draft_genomes($ncbi_draft_repository);
Phylosift::UpdateDB::get_ncbi_finished_genomes($ncbi_finished_repository);
Phylosift::UpdateDB::find_new_genomes( $ncbi_finished_repository, $result_repository, \@new_genomes );
Phylosift::UpdateDB::find_new_genomes( $ncbi_draft_repository,    $result_repository, \@new_genomes );
Phylosift::UpdateDB::find_new_genomes( $ebi_repository,           $result_repository, \@new_genomes );
Phylosift::UpdateDB::find_new_genomes( $local_repository,         $result_repository, \@new_genomes );
Phylosift::UpdateDB::qsub_updates( $result_repository, \@new_genomes );
Phylosift::UpdateDB::collate_markers( $result_repository, $marker_dir );
Phylosift::UpdateDB::assign_seqids( $marker_dir );
Phylosift::UpdateDB::build_marker_trees_fasttree($marker_dir,0);
Phylosift::UpdateDB::pd_prune_markers($marker_dir);
Phylosift::UpdateDB::build_marker_trees_fasttree($marker_dir,1);
Phylosift::UpdateDB::reconcile_with_ncbi( $newObject, $result_repository, $marker_dir, 1 );
Phylosift::UpdateDB::package_markers($marker_dir);
