#!/usr/bin/env perl
use warnings;
use strict;
use FindBin qw($Bin);
use lib "$Bin/../lib";
use Getopt::Long;
use Phylosift::Phylosift;
use Carp;
use Phylosift::Utilities qw(debug);
use Phylosift::UpdateDB;
die "Usage: phylosift_dbupdate.pl <data repository path>" unless @ARGV == 1;
my $repository               = $ARGV[0];
my $ebi_repository           = $repository . "/ebi";
my $ncbi_draft_repository    = $repository . "/ncbi_draft";
my $ncbi_finished_repository = $repository . "/ncbi_finished";
my $local_repository         = $repository . "/local";
my $result_repository        = $repository . "/processed";
my $marker_dir               = $repository . "/markers";
my $newObject                = new Phylosift::Phylosift();
my @new_genomes = ();
$newObject->readPhylosiftConfig();

Phylosift::Utilities::dataChecks(self=>$newObject);
Phylosift::UpdateDB::get_ebi_genomes(directory=>$ebi_repository);
Phylosift::UpdateDB::get_ncbi_draft_genomes(directory=>$ncbi_draft_repository);
Phylosift::UpdateDB::get_ncbi_finished_genomes(directory=>$ncbi_finished_repository);
Phylosift::UpdateDB::find_new_genomes( genome_directory=>$ncbi_finished_repository, results_directory=>$result_repository, files=>\@new_genomes );
Phylosift::UpdateDB::find_new_genomes( genome_directory=>$ncbi_draft_repository,    results_directory=>$result_repository,  files=>\@new_genomes );
Phylosift::UpdateDB::find_new_genomes( genome_directory=>$ebi_repository,           results_directory=>$result_repository,  files=>\@new_genomes );
Phylosift::UpdateDB::find_new_genomes( genome_directory=>$local_repository,         results_directory=>$result_repository,  files=>\@new_genomes );
Phylosift::UpdateDB::qsub_updates( results_directory=>$result_repository, files=>\@new_genomes );
Phylosift::UpdateDB::collate_markers( results_dir=>$result_repository, marker_dir=>$marker_dir );
Phylosift::UpdateDB::assign_seqids( marker_directory=>$marker_dir );
Phylosift::UpdateDB::update_rna( self=>$newObject, marker_dir => $marker_dir );
Phylosift::UpdateDB::update_ncbi_taxonomy(repository=>$repository);
debug "Updating NCBI tree and taxon map...";
Phylosift::UpdateDB::make_ncbi_tree_from_update( self=>$newObject, results_dir=>$result_repository, marker_dir=>$marker_dir );
debug "done\n";
Phylosift::UpdateDB::build_marker_trees_fasttree(directory=>$marker_dir,pruned=>0);
Phylosift::UpdateDB::pd_prune_markers(marker_directory=>$marker_dir);
Phylosift::UpdateDB::build_marker_trees_fasttree(marker_directory=>$marker_dir,pruned=>1);
Phylosift::UpdateDB::reconcile_with_ncbi( self=>$newObject, results_directory=>$result_repository, marker_directory=>$marker_dir, pruned=>1 );
Phylosift::UpdateDB::package_markers(marker_directory=>$marker_dir);
